Repository fedor-ivn/project-f, pull requests merged in 2023-09, with the labels that each got.

#3 Add more elaborate syntax tests
  tests/syntax.lispf
  tests/syntax/comments.lispf
  tests/syntax/lists.fail.lispf
  tests/syntax/lists.lispf
  tests/syntax/numbers.fail.lispf
  tests/syntax/numbers.lispf
  tests/syntax/quote.fail.lispf
  tests/syntax/quote.lispf
  tests/syntax/symbols.fail.lispf
  tests/syntax/symbols.lispf
Labels: enhancement

#6 Add a Readme
  Readme.md
Labels: documentation

#5 Add tests for special forms and built-in functions
  tests/functions/arithmetic.lispf
  tests/functions/comparisons.lispf
  tests/functions/eval.lispf
  tests/functions/lists.lispf
  tests/functions/logical.lispf
  tests/functions/predicates.lispf
  tests/semantic/control.lispf
  tests/semantic/functions.lispf
  tests/semantic/prog.lispf
  tests/semantic/quote.lispf
  tests/semantics.lispf
Labels: enhancement

#4 Lexical analysis
  .clang-format
  .gitignore
  src/main.cpp
  src/reader/scanner.cpp
  src/reader/scanner.h
  src/reader/token.cpp
  src/reader/token.h
Labels: enhancement

#9 Fix missing closing parenthesis
  tests/semantic/prog.lispf
Labels: bug

#10 Tokenize code from files or stdin
  src/main.cpp
Labels: enhancement

#16 Implement spans
  CMakeLists.txt
  src/main.cpp
  src/reader/scanner.cpp
  src/reader/scanner.h
  src/reader/span.cpp
  src/reader/span.h
  src/reader/token.cpp
  src/reader/token.h
Labels: enhancement
